Pipeline now includes apispec validation

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,3 +19,19 @@ steps:
     npm install
     npm run build
   displayName: 'npm install and build'
+
+- script: |
+    # By convention, we expose api specifications using files
+    #  in form api_<api-name>.yaml in the root of this project
+    valid=1
+    for apispec in $(ls api_*.yaml); do
+      echo "validating $apispec"
+      npx oval validate -p $apispec
+      result=$?
+      if [ ! $result = 0 ]; then
+        valid=0
+        echo "$apispec failed with code $result"
+      fi
+    done
+    [[ $valid = 1 ]] && exit 0 || exit 1
+    displayName: 'Validate API specifications'
