step target + network disconnect + restricted commands + extends

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -12,62 +12,30 @@ trigger:
 # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/step-target.md
 # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/step-target-restricted-mode.md
 
-resources:
-  containers:
-    - container: mycontainer
-      image: ubuntu:20.04
-      options: --name mycontainer1
+
+extends:
+  template: disconnected_containerized_execution_template.yml
+  parameters:
+    jobs:
+      - job: validate
+
+          - script: |
+              # By convention, we expose api specifications using files
+              #  in form api_<api-name>.yaml in the root of this project
+              valid=1
+              for apispec in $(ls api_*.yaml); do
+                echo "validating $apispec"
+                npx oval validate -p $apispec
+                result=$?
+                if [ ! $result = 0 ]; then
+                  valid=0
+                  echo "$apispec failed with code $result"
+                fi
+              done
+              [[ $valid = 1 ]] && exit 0 || exit 1
+            displayName: 'Validate API specifications'
 
 
 
 
-stages:
-    - stage: Static_analysis
-      dependsOn: []
-      jobs:
-          - job: validate
-            #pool:
-            #    vmImage: ubuntu-latest
-            #container:
-            #  mycontainer
 
-            steps:
-
-                - task: NodeTool@0
-                  inputs:
-                    versionSpec: '10.x'
-                  displayName: 'Install Node.js'
-                  target: mycontainer
-
-                - script: |
-                   npm install
-                   npm install -g oval
-                   npm run build
-                  displayName: 'npm install and build'
-                  target: mycontainer
-
-
-                - script: docker inspect mycontainer1 -f "{{json .NetworkSettings.Networks }}" | cut -c3-47
-                  target: host # reserved name for the host the worker is running on
-
-                - script: docker network disconnect $(docker inspect mycontainer1 -f "{{json .NetworkSettings.Networks }}" | cut -c3-47) mycontainer1
-                  target: host # reserved name for the host the worker is running on
-
-                - script: |
-                      # By convention, we expose api specifications using files
-                      #  in form api_<api-name>.yaml in the root of this project
-                      valid=1
-                      for apispec in $(ls api_*.yaml); do
-                        echo "validating $apispec"
-                        npx oval validate -p $apispec
-                        result=$?
-                        if [ ! $result = 0 ]; then
-                          valid=0
-                          echo "$apispec failed with code $result"
-                        fi
-                      done
-                      [[ $valid = 1 ]] && exit 0 || exit 1
-                  displayName: 'Validate API specifications'
-                  target:
-                      container: mycontainer
-                      commands: restricted
